apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onetimesecret-chart.onetimesecret.fullname" . }}
  labels:
    app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "onetimesecret-chart.onetimesecret.name" . }}
    spec:
      containers:
      - name: {{ include "onetimesecret-chart.onetimesecret.name" . }}
        image: "{{ .Values.onetimesecret.image.repository }}:{{ include "onetimesecret-chart.image.tag" . }}"
        ports:
        - containerPort: {{ include "onetimesecret-service.port" $ }}
        env:
        {{- if .Values.redis.enabled }}
        - name: REDIS_URL
          value: {{ include "onetimesecret-chart.redis.url" $ }}
        {{- end }}
        {{- if .Values.ingress.enabled }}
        - name: HOST
          {{- with (first .Values.ingress.hosts) }}
          value: "{{ .host }}"
          {{- end  }}
        {{- end }}
        {{- range $key, $value := .Values.onetimesecret.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
    {{- if .Values.onetimesecret.nodeSelector }}
      nodeSelector: {{ toYaml .Values.onetimesecret.nodeSelector | nindent 8 }}
    {{- end }}